name: TimingSystem
main: me.makkuusen.timing.system.TimingSystem
version: 1.5
authors: [Markus Hellquist (Makkuusen)]
depend: [WorldEdit]
softdepend: [HolographicDisplays, Multiverse-Core]
api-version: '1.20'
commands:
   track:
      description: Command for managing tracks.
      aliases: [t]
   timetrial:
      description: Command for running tracks.
      aliases: [tt]
   event:
      description: Command for events.
      aliases: []
   heat:
      description: Command for heats.
      aliases: []
   round:
      description: Command for rounds.
      aliases: []
   timingsystem:
      description: Command for server settings
      aliases: [ts]
   boat:
      description: Spawns a boat
      aliases: [b]
   race:
      description: Quickraces

permissions:

   track.admin:
      description: Player can admin tracks
      default: op
   event.admin:
      description: Player can admin events
      default: op
   event.sign:
      description: Allows signing to sign to closed events
      default: op
   event.sign.others:
      description: Allows admin per to sign others into events
      default: op
   race.admin:
      description: Allows admin of quickraces
      default: op