name: TimingSystem
main: me.makkuusen.timing.system.TimingSystem
version: 1.2
authors: [Markus Hellquist (Makkuusen)]
depend: [WorldEdit]
softdepend: [HolographicDisplays, Multiverse-Core]
api-version: 1.19
commands:
   track:
      description: Command for managing tracks.
      aliases: [t]
   timetrial:
      description: Command for running tracks.
      aliases: [tt]
   event:
      description: Command for events.
      aliases: []
   heat:
      description: Command for heats.
      aliases: []
   round:
      description: Command for rounds.
      aliases: []

permissions:

   track.admin:
      description: Player can admin tracks
      default: op
   event.admin:
      description: Player can admin events
      default: op