name: TimingSystem
main: me.makkuusen.timing.system.TimingSystem
version: '2.0'
authors: [Makkuusen, Pigalala, GitHub Repository Contributors]
depend: [WorldEdit]
softdepend: [HolographicDisplays, DecentHolograms, Multiverse-Core, PlaceholderAPI]
api-version: '1.20'
commands:
   track:
      description: Command for information about tracks.
      aliases: [t]
   trackedit:
      description: Command for editing tracks.
      aliases: [te]
   timetrial:
      description: Command for running tracks.
      aliases: [tt]
   event:
      description: Command for events.
      aliases: []
   heat:
      description: Command for heats.
      aliases: []
   round:
      description: Command for rounds.
      aliases: []
   timingsystem:
      description: Command for server settings
      aliases: [ts]
   boat:
      description: Spawns a boat
      aliases: [b]
   race:
      description: Quickraces
   reset:
      description: Resets time trials for players.
      aliases: [re]

permissions:
   timingsystem.packs.default:
      description: Default commands for all players
      default: true
      children:
         timingsystem.track.view.mytimes: true
         timingsystem.track.session.timetrial: true
         timingsystem.track.view.times: true
         timingsystem.track.info: true
         timingsystem.settings: true
         timingsystem.boat: true
         timingsystem.reset: true
         timingsystem.timetrial.menu: true
         timingsystem.timetrial.cancel: true
         timingsystem.timetrial.random: true
         timingsystem.race.join: true
         timingsystem.race.leave: true
         timingsystem.event.select: true
         timingsystem.event.spectate: true
         timingsystem.event.info: true
         timingsystem.event.sign: true
         timingsystem.event.reserve: true
         timingsystem.event.listsigns: true
         timingsystem.event.list: true
         timingsystem.round.info: true
         timingsystem.round.list: true
         timingsystem.round.results: true
         timingsystem.heat.info: true
         timingsystem.heat.list: true
         timingsystem.heat.results: true
         timingsystem.heat.quit: true

   timingsystem.packs.trackbuilder:
      description: Player has the tools to build a track
      default: false
      children:
         timingsystem.packs.default: true
         timingsystem.track.view.regions: true
         timingsystem.track.view.locations: true
         timingsystem.trackedit.info: true
         timingsystem.trackedit.create: true
         timingsystem.trackedit.view: true
         timingsystem.trackedit.options: true
         timingsystem.trackedit.boatutilsmode: true
         timingsystem.trackedit.name: true
         timingsystem.trackedit.item: true
         timingsystem.trackedit.region: true
         timingsystem.trackedit.location: true

   timingsystem.packs.trackadmin:
      description: Player has all track commands
      default: op
      children:
         timingsystem.packs.trackbuilder: true
         timingsystem.track.here: true
         timingsystem.track.menu: true
         timingsystem.track.tp: true
         timingsystem.track.view.here: true
         timingsystem.track.view.alltimes: true
         timingsystem.track.reload: true
         timingsystem.track.delete.besttime: true
         timingsystem.track.delete.alltimes: true
         timingsystem.track.updateleaderboards: true
         timingsystem.trackedit.delete.track: true
         timingsystem.trackedit.move: true
         timingsystem.trackedit.open: true
         timingsystem.trackedit.timetrial: true
         timingsystem.trackedit.weight: true
         timingsystem.trackedit.tag: true
         timingsystem.trackedit.type: true
         timingsystem.trackedit.owner: true
         timingsystem.trackedit.contributors: true

   timingsystem.packs.racehoster:
      description: Player has the tools to host quick races
      default: false
      children:
         timingsystem.race.create: true
         timingsystem.race.start: true
         timingsystem.race.end: true

   timingsystem.packs.eventhoster:
      description: Player has the tools to host events
      default: false
      children:
         timingsystem.packs.default: true
         timingsystem.event.create: true
         timingsystem.event.start: true
         timingsystem.event.finish: true
         timingsystem.event.set.track: true
         timingsystem.event.set.signs: true
         timingsystem.event.signothers: true
         timingsystem.event.broadcast.clicktosign: true
         timingsystem.event.broadcast.clicktoreserve: true
         timingsystem.round.create: true
         timingsystem.round.delete: true
         timingsystem.round.finish: true
         timingsystem.round.fillheats: true
         timingsystem.round.removedrivers: true
         timingsystem.heat.start: true
         timingsystem.heat.finish: true
         timingsystem.heat.load: true
         timingsystem.heat.reset: true
         timingsystem.heat.remove: true
         timingsystem.heat.create: true
         timingsystem.heat.set.laps: true
         timingsystem.heat.set.pits: true
         timingsystem.heat.set.startdelay: true
         timingsystem.heat.set.timelimit: true
         timingsystem.heat.set.maxdrivers: true
         timingsystem.heat.set.setdriverposition: true
         timingsystem.heat.set.reversegrid: true
         timingsystem.heat.sort.tt: true
         timingsystem.heat.sort.random: true
         timingsystem.shortname.others: true

   timingsystem.packs.eventadmin:
      description: Player has access to all event related commands
      default: op
      children:
         timingsystem.packs.eventhoster: true
         timingsystem.packs.racehoster: true
         timingsystem.event.delete: true

   timingsystem.packs.admin:
      description: Player has access to most commands
      default: op
      children:
         timingsystem.packs.eventadmin: true
         timingsystem.packs.trackadmin: true
         timingsystem.settings.override: true

