name: TimingSystem
main: me.makkuusen.timing.system.TimingSystem
version: 1.8
authors: [Makkuusen, GitHub Repository Contributors]
depend: [WorldEdit]
softdepend: [HolographicDisplays, DecentHolograms, Multiverse-Core, PlaceholderAPI]
api-version: '1.20'
commands:
   track:
      description: Command for managing tracks.
      aliases: [t]
   timetrial:
      description: Command for running tracks.
      aliases: [tt]
   event:
      description: Command for events.
      aliases: []
   heat:
      description: Command for heats.
      aliases: []
   round:
      description: Command for rounds.
      aliases: []
   timingsystem:
      description: Command for server settings
      aliases: [ts]
   boat:
      description: Spawns a boat
      aliases: [b]
   race:
      description: Quickraces
   reset:
      description: Resets time trials for players.
      aliases: [re]
   trackexchange:
      description: Copy/paste for tracks.
      aliases: [te]

permissions:

   track.admin:
      description: Player can admin tracks
      default: op
   track.operator:
      description: Player can access operator only track information.
      default: op
   event.admin:
      description: Player can admin events
      default: op
   event.sign:
      description: Allows signing to sign to closed events
      default: op
   event.sign.others:
      description: Allows admin per to sign others into events
      default: op
   race.admin:
      description: Allows admin of quickraces
      default: op
