package me.makkuusen.timing.system.text;


public enum Error {
    GENERIC,
    NOT_NOW,
    FAILED_TELEPORT,
    FAILED_TO_REMOVE,
    FAILED_TO_REMOVE_TAG,
    FAILED_TO_ADD_TAG,
    FAILED_TO_CREATE_TAG,
    ONLY_PLAYERS,
    WORLD_NOT_LOADED,
    SYNTAX,
    NUMBER_FORMAT,
    LENGTH_EXCEEDED,
    NAME_FORMAT,
    COLOR_FORMAT,
    SELECTION,
    NO_ZERO_INDEX,
    NOTHING_TO_REMOVE,
    NOTHING_TO_RESTORE,
    PLAYER_NOT_FOUND,
    TRACKS_NOT_FOUND,
    REGIONS_NOT_FOUND,
    PAGE_NOT_FOUND,
    ITEM_NOT_FOUND,
    TAG_NOT_FOUND,
    TRACK_IS_CLOSED,
    TRACK_EXISTS,
    RACE_EXISTS,
    INVALID_TRACK_TYPE,
    INVALID_TRACK_NAME,
    INVALID_TRACK_MODE,
    INVALID_NAME,
    NO_EVENT_SELECTED,
    PERMISSION_DENIED;

    Error() {}
}